version: '3.8'
name: 'sri_hri'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Password123!" # Replace with a strong password
    volumes:
      - ./mssql_data:/var/opt/mssql
    restart: unless-stopped
